foreground              #a6a6a6
background              #080808
selection_foreground    #c4c4c4
selection_background    #1a1a1a

cursor                  #c4c4c4
cursor_text_color       #080808

url_color               #8a8a8a
active_border_color     #1a1a1a
inactive_border_color   #121212

color0  #000000
color8  #3d3d3d
color1  #4a4a4a
color9  #686868
color2  #5c5c5c
color10 #a6a6a6
color3  #666666
color11 #b0b0b0
color4  #707070
color12 #b8b8b8
color5  #7a7a7a
color13 #d0d0d0
color6  #848484
color14 #c0c0c0
color7  #a6a6a6
color15 #e0e0e0
