classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
color:
  when: never
date: "+%a %b %e %H:%M:%S %Y"
dereference: false
ignore-globs: []
indicators: false
layout: grid
recursion:
  enabled: false
  depth: 3
size: default
sorting:
  column: name
  reverse: false
  dir-grouping: first
no-symlink: false
total-size: false
symlink-arrow: ⇒
hyperlink: never
